name: Change Pausing State
on:
  workflow_dispatch:
    inputs:
      in_pause:
        description: 'Tick to pause, do not tick to unpause'
        required: true
        type: boolean


jobs:
  do_pause:
    runs-on: ubuntu-latest

    env:
      IN_PAUSE: ${{ inputs.in_pause }}

      KDA_TOOL_VERSION: "1.2"
      ETH_RPC_URL: ${{ vars.ETH_RPC_URL }}
      KADENA_RPC_URL: ${{ vars.KADENA_RPC_URL }}
      PAUSE_HOOK_ADDR: "0x9e55757C3EF8bcA9015F9d0A6287ccE79215cA07"
      PAUSE_ISM_ADDR: "0xDeC953FDf8890AEDb5C549dF472A1231baBcE8AC"

      KDA_KEYFILE: keys/gh_pauser.yaml.gpg
      ETH_KEYSTORE: keys/eth_ism_pauser.json
      ETH_PRIORITY_GAS_PRICE: "0.01gwei"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Checkout keys repos
        uses: actions/checkout@v6
        with:
          repository: kinesis-bridge/kadena-hyperlane-keys
          path: keys

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install KDA tool
        run: |
          ARCHIVE=kda-tool-${KDA_TOOL_VERSION}-ubuntu-24.04.tar.gz
          wget -nv https://github.com/kda-community/kda-tool/releases/download/${KDA_TOOL_VERSION}/$ARCHIVE
          tar xzf $ARCHIVE
          echo "KDA=kda-tool-${KDA_TOOL_VERSION}/kda" >> "$GITHUB_ENV"

      - name: Configure KDA tool
        run: |
          mkdir -p ~/.config/kda
          jq -n --arg value "$KADENA_RPC_URL" '{networks: {mainnet01: $value}}' > ~/.config/kda/config.json

      - name: Find Kadena Public key
        id: kda_pubkey
        env:
          PASSWORD: ${{ secrets.KDA_PAUSER_PASSWORD }}
        shell: bash
        run: |
          set -euo pipefail
          KDA_PUBKEY=$(echo $PASSWORD | gpg -d --batch --yes --passphrase-fd 0 $KDA_KEYFILE | grep -oP '^public:\s*\K.*')
          echo "Public Key: $KDA_PUBKEY"
          echo "KDA_PUBKEY=$KDA_PUBKEY" >> "$GITHUB_ENV"

      - name: Find Eth Address and nonce
        env:
          PASSWORD: ${{ secrets.ETH_PAUSER_PASSWORD }}

        shell: bash
        run: |
          set -euo pipefail
          ETH_ADDR=$(cast wallet address --password $PASSWORD)
          NONCE=$(cast nonce $ETH_ADDR)

          echo "Eth Address: $ETH_ADDR"
          echo "ETH_ADDR=$ETH_ADDR" >> "$GITHUB_ENV"
          echo "ETH_NONCE=$NONCE" >> "$GITHUB_ENV"


      - name: Pause Kadena contract
        continue-on-error: true
        env:
          PASSWORD: ${{ secrets.KDA_PAUSER_PASSWORD }}

        shell: bash
        run: |
          # Prepare config file
          echo "key: \"$KDA_PUBKEY\"" >> config.yaml
          echo "in-pause: \"$IN_PAUSE\"" >> config.yaml

          # Gen the transaction
          $KDA gen -t do_pause.tkpl -d config.yaml

          # Sign
          echo $PASSWORD | gpg -d --batch --yes --passphrase-fd 0 $KDA_KEYFILE| $KDA sign tx.yaml -k -
          RESULT=$($KDA local tx.json)
          echo $RESULT | jq

      - name: Pause Eth Hook
        continue-on-error: true
        env:
          PASSWORD: ${{ secrets.ETH_PAUSER_PASSWORD }}

        shell: bash
        run: |
          echo "Start"
          ZERO=$(cast address-zero)

          echo "Got Zero"
          CURRENT_VALUE=$(cast call $PAUSE_HOOK_ADDR "paused()(bool)" --password $PASSWORD)

          echo "$CURRENT_VALUE" == "$IN_PAUSE"

          if [ "$CURRENT_VALUE" == "$IN_PAUSE" ]
          then
            echo "Hook contract already in state: $CURRENT_VALUE"
          else
            if [ "$IN_PAUSE" == "true" ]
              then
                cast send $PAUSE_HOOK_ADDR "pause()" --async --nonce $ETH_NONCE --password $PASSWORD

              else
                cast send $PAUSE_HOOK_ADDR "unpause()" --async --nonce $ETH_NONCE --password $PASSWORD
            fi

            NEW_NONCE=$((ETH_NONCE + 1))
            echo "ETH_NONCE=$NEW_NONCE" >> "$GITHUB_ENV"
          fi
